server:
  port: 8083
spring:

  application:
    name: Notification-Utility


  kafka:
    bootstrap-servers: ${KAFKA_SERVER_URL}
    properties:
      security:
        protocol: SASL_SSL
        sasl:
          mechanism: SCRAM-SHA-256
          jaas:
            config: org.apache.kafka.common.security.scram.ScramLoginModule required username="avnadmin" password=${KAFKA_SERVER_PASSWORD};
    consumer:
      auto-offset-reset: earliest
      group-id : notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "[spring.deserializer.value.delegate.class]": "org.springframework.kafka.support.serializer.JsonDeserializer"
        "[spring.json.trusted.packages]": ${KAFKA_TRUSTED_PACKAGES}
        "[spring.json.value.default.type]": "dev.gamgrind.Notification_Utility.dto.EmailNotificationEvent"
        "[spring.json.use.type.headers]": false

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer



  mail:
    host : ${SMTP_SERVER_HOST}
    port : ${SMTP_SERVER_PORT}
    username : ${SMTP_SERVER_USERNAME}
    password : ${SMTP_SERVER_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable : true

